### ISSUE TITLE
cx_Freeze.freezer.ConfigError: no base named Win32GUI

### ISSUE THREAD

**Issue by rgaufman** [pedrolemoz/MagicMagnet#5]
I'm on a mac, I don't think I have Win32GUI - how to build on mac, or alternatively is there a command line version of this?

I see this when I try to build:

```
MagicMagnet git:(master) $ python3 build_application.py build
running build
running build_exe
Traceback (most recent call last):
  File "build_application.py", line 23, in <module>
    executables = [target]
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/dist.py", line 340, in setup
    distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/dist.py", line 210, in run
    zipExcludePackages = self.zip_exclude_packages)
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 105, in __init__
    self._VerifyConfiguration()
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 475, in _VerifyConfiguration
    executable._VerifyConfiguration(self)
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 673, in _VerifyConfiguration
    self._GetBaseFileName()
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 690, in _GetBaseFileName
    raise ConfigError("no base named %s", name)
cx_Freeze.freezer.ConfigError: no base named Win32GUI
```

**Comment by pedrolemoz** [comment]
Thanks for posting this issue here.

I have not tested this project in Macintosh, but accordingly to the [cx_Freeze documentation](https://cx-freeze.readthedocs.io/), you'll need a different command.

Please try ```python3 build_application.py bdist_mac``` or ```python3 build_application.py bdist_dmg```

Reference: https://cx-freeze.readthedocs.io/en/latest/distutils.html#bdist-mac

**Comment by telegrambotdev** [comment]
> Thanks for posting this issue here.
> 
> I have not tested this project in Macintosh, but accordingly to the [cx_Freeze documentation](https://cx-freeze.readthedocs.io/), you'll need a different command.
> 
> Please try `python3 build_application.py bdist_mac` or `python3 build_application.py bdist_dmg`.
> 
> You may need to change the `build_application.py` too in order to build a MacOS version. I have no idea how to do it, but your efforts would be highly appreciated if you can do.
> 
> Reference: https://cx-freeze.readthedocs.io/en/latest/distutils.html#bdist-mac

i am getting same error for my ubuntu server.what should do ?
